name: MacOS

on:
  push: {}
  pull_request: {}

env:
  PROJECT_NAME: "QuickCut"
  QT_VERSION: 5.15.0

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: "MacOS Latest",
            os: "macos-latest",
            artifact: "MacOS",
            build_type: "Release",
            cmake_generator: "",
            cmake_build_args: "-j8",
          }

    steps:
    - uses: actions/checkout@v2

    # - name: Install conan Packge-Manager
    #   id: install_pm
    #   run: |
    #     pip install conan
    #     conan -v
    #     conan profile new default --detect --force

    # - name: Download Qt modules
    #   id: qt
    #   uses: jurplel/install-qt-action@v2
    #   with:
    #     version: "${{ env.QT_VERSION }}"
    #     modules: core gui widgets
    #     arch: "${{ matrix.config.xxxx }}"

    # - name: CMake configure
    #   id: cmake_configure
    #   run: |
    #     mkdir build && cd build
    #     conan install ..
    #     cmake .. ${{ matrix.config.cmake_generator }} -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -DUSE_CONAN_PM=ON

    # - name: CMake build
    #   id: cmake_build
    #   run: |
    #     cd build
    #     cmake --build . --config ${{ matrix.config.build_type }} -- ${{ matrix.config.cmake_build_args }}

    # - uses: actions/upload-artifact@v2
    #   id: upload_artifact
    #   with:
    #     name: ${{ matrix.config.artifact }}
    #     path: ./build/bin/
